# Generated by Django 3.1 on 2020-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('manager', models.CharField(max_length=60)),
                ('type_of_participant', models.CharField(max_length=60)),
                ('foundation_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
